# Generated by Django 3.1.7 on 2021-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the website', max_length=100)),
                ('favicon', models.FileField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('about', models.TextField()),
            ],
        ),
    ]
