# Generated by Django 3.1.7 on 2021-04-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='name',
            field=models.CharField(help_text='Name of the website', max_length=100),
        ),
    ]
