# Generated by Django 3.1.7 on 2021-04-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_siteinfo_apple_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('tik_tok', 'Tik Tok')], max_length=100)),
                ('link', models.URLField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='main.siteinfo')),
            ],
        ),
    ]
