# Generated by Django 3.1.7 on 2021-04-02 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(blank=True, max_length=10)),
                ('reg_no', models.CharField(blank=True, max_length=10)),
                ('is_governor', models.BooleanField(default=False, help_text='Flag to indicate that                                       the student is a class governor')),
                ('is_deputy', models.BooleanField(default=False, help_text='Flag to indicate that                                     the student is a class deputy')),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('basic_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_data', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True)),
                ('HOD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uni.lecturer')),
            ],
        ),
    ]
