# Generated by Django 3.1.7 on 2021-04-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='link',
            field=models.SlugField(blank=True),
        ),
    ]
