# Generated by Django 3.2 on 2021-04-16 03:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symposium',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='symposium',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 16, 3, 44, 53, 918205, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symposium',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
