# Generated by Django 3.2 on 2021-04-22 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_symposiumbroadcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symposiumbroadcast',
            name='archive',
        ),
        migrations.AddField(
            model_name='symposiumbroadcast',
            name='expire_by',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 14, 27, 59, 842436, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
