# Generated by Django 3.1.7 on 2021-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_student_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_photograph',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
