# Generated by Django 3.1.7 on 2021-04-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_auto_20210408_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='local_government',
        ),
    ]
