# Generated by Django 3.2.8 on 2021-10-19 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_auto_20211016_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableunit',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='uni.timetable'),
        ),
    ]
