# Generated by Django 3.1.7 on 2021-04-15 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_remove_student_local_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphonenumber',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='uni.student'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('symposium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='uni.symposium')),
            ],
        ),
    ]
