# Generated by Django 3.2.8 on 2021-10-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_alter_timetableunit_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='symposium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='uni.symposium'),
        ),
    ]
