# Generated by Django 3.1.7 on 2021-04-15 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0007_auto_20210415_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 15, 6, 15, 30, 163277, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
