# Generated by Django 3.1.7 on 2021-04-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0010_auto_20210415_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='e.g MAT-101     (all capital letters)', max_length=10),
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.course')),
                ('symposium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='uni.symposium')),
            ],
        ),
    ]
