# Generated by Django 3.1.7 on 2021-04-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0012_auto_20210415_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='course',
            new_name='offered_course',
        ),
    ]
