# Generated by Django 3.1.7 on 2021-04-16 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0014_auto_20210415_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symposium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='uni.symposium')),
            ],
        ),
        migrations.AddField(
            model_name='offeredcourse',
            name='unit',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TimetableUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('E', 'Exam'), ('P', 'Practical')], max_length=1)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='uni.offeredcourse')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='uni.timetable')),
            ],
        ),
    ]
