# Generated by Django 3.1.7 on 2021-04-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0015_auto_20210416_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AddField(
            model_name='timetableunit',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
