# Generated by Django 3.1.7 on 2021-04-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0016_auto_20210416_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
